# Generated by the rules_elixir_mix toolchain extension.

load(
    "@rules_elixir_mix//:defs.bzl",
    "elixir_prebuilt_release",
    "elixir_toolchain",
    "otp_prebuilt_release",
    "otp_toolchain",
)

otp_prebuilt_release(
    name = "otp",
    crypto_sdk = %{CRYPTO_SDK},
    erlexec = "%{ERLEXEC}",
    fips = "%{FIPS}",
    srcs = ["%{OTP_RUNTIME}"],
    static_crypto_nif = %{STATIC_CRYPTO_NIF},
    version = "%{OTP_VERSION}",
    version_marker = "%{OTP_VERSION_MARKER}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_prebuilt_release(
    name = "runtime",
    home_marker = "%{ELIXIR_HOME_MARKER}",
    otp = ":otp",
    srcs = ["%{ELIXIR_RUNTIME}"],
    version = "%{ELIXIR_VERSION}",
    version_marker = "%{ELIXIR_VERSION_MARKER}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_toolchain(
    name = "elixir",
    elixir = ":runtime",
    native_bash = %{BASH},
    native_make = %{MAKE},
    native_perl = %{PERL},
    native_posix_tools = [
%{POSIX_TOOLS}    ],
)

otp_toolchain(
    name = "otp_toolchain_impl",
    otp = ":otp",
)

toolchain(
    name = "otp_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":otp_toolchain_impl",
    toolchain_type = "@rules_elixir_mix//:otp_toolchain_type",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir_mix//:toolchain_type",
)
