# Generated by the rules_elixir_mix toolchain extension.

load(
    "@rules_elixir_mix//:defs.bzl",
    "elixir_source_release",
    "elixir_toolchain",
    "otp_prebuilt_release",
    "otp_source_release",
    "otp_toolchain",
)

otp_prebuilt_release(
    name = "bootstrap_otp",
    erlexec = "%{BOOTSTRAP_ERLEXEC}",
    srcs = ["%{BOOTSTRAP_RUNTIME}"],
    version = "%{BOOTSTRAP_OTP_VERSION}",
    version_marker = "%{BOOTSTRAP_VERSION_MARKER}",
    exec_compatible_with = [
%{BOOTSTRAP_EXEC_CONSTRAINTS}    ],
)

otp_source_release(
    name = "otp",
    bash = "%{BASH}",
    bootstrap_launcher = "%{BOOTSTRAP_LAUNCHER}",
    bootstrap_otp = ":bootstrap_otp",
    configure_options = [
%{CONFIGURE_OPTIONS}    ],
    copts = [
%{COPTS}    ],
    crypto_sdk = %{CRYPTO_SDK},
    cross_compile = %{CROSS_COMPILE},
    cxxopts = [
%{CXXOPTS}    ],
    jobs = %{JOBS},
    linkopts = [
%{LINKOPTS}    ],
    make = "%{MAKE}",
    make_options = [
%{MAKE_OPTIONS}    ],
    perl = %{PERL},
    posix_tools = [
%{POSIX_TOOLS}    ],
    source_directories = "%{OTP_SOURCE_DIRECTORIES}",
    srcs = ["%{OTP_SOURCES}"],
    fips = "%{FIPS}",
    static_crypto_nif = %{STATIC_CRYPTO_NIF},
    version = "%{OTP_VERSION}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_source_release(
    name = "runtime",
    bash = "%{BASH}",
    jobs = %{ELIXIR_JOBS},
    make = "%{MAKE}",
    make_options = [
%{ELIXIR_MAKE_OPTIONS}    ],
    otp = ":otp",
    posix_tools = [
%{POSIX_TOOLS}    ],
    srcs = ["%{ELIXIR_SOURCES}"],
    version = "%{ELIXIR_VERSION}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_toolchain(
    name = "elixir",
    elixir = ":runtime",
    native_bash = "%{BASH}",
    native_make = "%{MAKE}",
    native_perl = %{PERL},
    native_posix_tools = [
%{POSIX_TOOLS}    ],
)

otp_toolchain(
    name = "otp_toolchain_impl",
    otp = ":otp",
)

toolchain(
    name = "otp_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":otp_toolchain_impl",
    toolchain_type = "@rules_elixir_mix//:otp_toolchain_type",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir_mix//:toolchain_type",
)
