# Generated by the rules_elixir_mix toolchain extension.

load(
    "@rules_elixir_mix//:defs.bzl",
    "elixir_source_release",
    "elixir_toolchain",
    "otp_prebuilt_release",
    "otp_runtime_smoke_test",
    "otp_source_release",
    "otp_toolchain",
)

%{BOOTSTRAP_DECLARATION}

otp_runtime_smoke_test(
    name = "bootstrap_smoke_test",
    otp = %{BOOTSTRAP_OTP},
    tags = ["block-network"],
    target_compatible_with = [
%{BOOTSTRAP_EXEC_CONSTRAINTS}    ],
)

otp_source_release(
    name = "otp",
    bash = "%{BASH}",
    bootstrap_otp = %{BOOTSTRAP_OTP},
    configure_options = [
%{CONFIGURE_OPTIONS}    ],
    copts = [
%{COPTS}    ],
    crypto_sdk = %{CRYPTO_SDK},
    cross_compile = %{CROSS_COMPILE},
    cxxopts = [
%{CXXOPTS}    ],
    jobs = %{JOBS},
    jit = "%{JIT}",
    libc = "%{LIBC}",
    linkopts = [
%{LINKOPTS}    ],
    make = "%{MAKE}",
    make_options = [
%{MAKE_OPTIONS}    ],
    otp_fully_static = %{OTP_FULLY_STATIC},
    perl = %{PERL},
    posix_tools = [
%{POSIX_TOOLS}    ],
    source_directories = "%{OTP_SOURCE_DIRECTORIES}",
    srcs = ["%{OTP_SOURCES}"],
    fips = "%{FIPS}",
    static_crypto_nif = %{STATIC_CRYPTO_NIF},
    target_arch = "%{TARGET_ARCH}",
    version = "%{OTP_VERSION}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_source_release(
    name = "runtime",
    bash = "%{BASH}",
    jobs = %{ELIXIR_JOBS},
    make = "%{MAKE}",
    make_options = [
%{ELIXIR_MAKE_OPTIONS}    ],
    otp = ":otp",
    posix_tools = [
%{POSIX_TOOLS}    ],
    srcs = ["%{ELIXIR_SOURCES}"],
    version = "%{ELIXIR_VERSION}",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
%{TARGET_CONSTRAINTS}    ],
)

elixir_toolchain(
    name = "elixir",
    elixir = ":runtime",
    native_bash = "%{BASH}",
    native_make = "%{MAKE}",
    native_perl = %{PERL},
    native_posix_tools = [
%{POSIX_TOOLS}    ],
)

otp_toolchain(
    name = "otp_toolchain_impl",
    otp = ":otp",
)

toolchain(
    name = "otp_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":otp_toolchain_impl",
    toolchain_type = "@rules_elixir_mix//:otp_toolchain_type",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir_mix//:toolchain_type",
)

# The runtime wrapper carries the target loader and libraries in runfiles, so
# tests execute on the build-host OS/CPU while retaining the runtime ABI as a
# target constraint. This avoids falsely advertising a target libc on the
# execution platform under Bazel's default test-toolchain contract.
toolchain(
    name = "test_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = "@bazel_tools//tools/test:empty_toolchain",
    toolchain_type = "@bazel_tools//tools/test:default_test_toolchain_type",
)
