# Generated by the rules_elixir_mix toolchain extension.

load(
    "@rules_elixir_mix//:defs.bzl",
    "elixir_prebuilt_release",
    "elixir_toolchain",
    "otp_prebuilt_release",
    "otp_toolchain",
)

%{OTP_DECLARATION}

%{ELIXIR_DECLARATION}

elixir_toolchain(
    name = "elixir",
    elixir = ":runtime",
    native_bash = %{BASH},
    native_make = %{MAKE},
    native_perl = %{PERL},
    native_posix_tools = [
%{POSIX_TOOLS}    ],
)

otp_toolchain(
    name = "otp_toolchain_impl",
    otp = ":otp",
)

toolchain(
    name = "otp_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":otp_toolchain_impl",
    toolchain_type = "@rules_elixir_mix//:otp_toolchain_type",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir_mix//:toolchain_type",
)

toolchain(
    name = "test_toolchain",
    exec_compatible_with = [
%{EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:runtime_%{NAME}",
%{TARGET_CONSTRAINTS}    ],
    toolchain = "@bazel_tools//tools/test:empty_toolchain",
    toolchain_type = "@bazel_tools//tools/test:default_test_toolchain_type",
)
