"""Pure-Starlark generated asset used by the checked-in integration test."""

def _generated_asset_impl(ctx):
    output = ctx.actions.declare_file(ctx.attr.filename or ctx.label.name + ".txt")
    ctx.actions.write(output, ctx.attr.content)
    return [DefaultInfo(files = depset([output]))]

generated_asset = rule(
    implementation = _generated_asset_impl,
    attrs = {
        "content": attr.string(default = "generated by a declared Bazel action\n"),
        "filename": attr.string(),
    },
)
